# Generated by Django 5.2.3 on 2025-07-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(db_index=True, verbose_name='Strava Activity ID'),
        ),
    ]
