# Generated by Django 5.2.3 on 2025-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0002_customuser_birth_year_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='chip_time',
            field=models.IntegerField(default=2, verbose_name='Official Chip Time (seconds)'),
            preserve_default=False,
        ),
    ]
