# Generated by Django 5.2.3 on 2025-07-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0003_alter_activity_strava_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weekly_run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_run_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_run_elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_run_elevation_gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_run_moving_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_run_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_run_elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_run_elevation_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='all_time_run_moving_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recent_run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recent_run_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recent_run_elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recent_run_elevation_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recent_run_moving_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ytd_run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ytd_run_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ytd_run_elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ytd_run_elevation_gain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ytd_run_moving_time',
            field=models.IntegerField(default=0),
        ),
    ]
