# Generated by Django 5.2.3 on 2025-07-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0003_activity_chip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='chip_time',
        ),
    ]
