# Generated by Django 5.2.3 on 2025-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0004_customuser_weekly_run_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recent_avg_heartrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recent_max_heartrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_avg_heartrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weekly_max_heartrate',
            field=models.FloatField(default=0.0),
        ),
    ]
