# Generated by Django 5.2.3 on 2025-07-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0005_activity_chip_time_activity_race_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='race_distance',
            field=models.CharField(blank=True, choices=[('1km', '1 km'), ('1mi', '1 mile'), ('5km', '5 km'), ('5mi', '5 mile'), ('10km', '10 km'), ('15km', '15 km'), ('10mi', '10 mile'), ('HM', 'Half Marathon'), ('30km', '30 km'), ('FM', 'Marathon'), ('50km', '50 km'), ('100km', '100 km'), ('150km', '150 km'), ('100mi', '100 mile'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Race Distance'),
        ),
    ]
