# Generated by Django 5.2.3 on 2025-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_group_admin'),
        ('strava_web', '0005_customuser_recent_avg_heartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='members', related_query_name='member', to='auth.group', verbose_name='groups'),
        ),
    ]
