# Generated by Django 5.2.3 on 2025-07-26 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0006_alter_activity_race_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date_local'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
