# Generated by Django 5.2.3 on 2025-07-15 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_alter_group_announcement_alter_group_description'),
        ('strava_web', '0006_alter_customuser_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待批准'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='申请状态')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auth.group', verbose_name='申请群组')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '群组申请',
                'verbose_name_plural': '群组申请',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
