# Generated by Django 5.2.3 on 2025-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava_web', '0008_alter_activity_race_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nick Name'),
        ),
    ]
